# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1689e88c07c4204f538bd55f5592ed978add182db93c27156ab3bd1cb6c06adc9d8709ff74110a326c8ea080ada0a872f5ed4a8845c02553fafdd191092ebee4

test:
  secret_key_base: 0b99df90c7563f1238f3cbb0f4d101606897ba8fd670fcabafb8ef170a649c7e1e61e00f2a9307e4982254cd5b1642c3cd5630d653de84a38b49d6b0d9356906

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
